#!/bin/bash

build() {
    add_module dm-cache
    add_module dm-cache-mq
    add_module dm-snapshot
    add_module rd

    add_binary "blockdev"
    add_binary "dmsetup"
    add_binary "dd"
    add_binary "od"
    add_binary "partx"
    add_binary "kpartx"

    add_file "/etc/memroot.conf"

    add_file "/usr/lib/udev/rules.d/10-dm.rules"
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
    add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"
    add_file "/usr/lib/udev/kpartx.rules" "/usr/lib/udev/rules.d/15-kpartx.rules"
    add_file "/usr/lib/udev/kpartx_id"

    add_runscript
}

help() {
    cat <<HELPEOF
This hook prepares the root device cached and snapshotted in memory.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
